"""Remove nullable=False to allow for delete-orphan

Revision ID: 1e2ed811e88d
Revises: 7b8c5950c5cc
Create Date: 2021-01-13 11:27:58.636321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2ed811e88d'
down_revision = '7b8c5950c5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('o_auth1_token', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('scheduled_job', schema=None) as batch_op:
        batch_op.alter_column('update_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_job', schema=None) as batch_op:
        batch_op.alter_column('update_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('o_auth1_token', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
