"""Increase realm id length

Revision ID: 3e1e3b0b2643
Revises: 7cd00819c52b
Create Date: 2021-11-25 22:40:22.378251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1e3b0b2643'
down_revision = '7cd00819c52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=36))

    with op.batch_alter_table('update_realm', schema=None) as batch_op:
        batch_op.alter_column('realm_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=36))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_realm', schema=None) as batch_op:
        batch_op.alter_column('realm_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=30))

    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=30))

    # ### end Alembic commands ###
