"""Remove unique constraint on username

Revision ID: 5a0eb5916ecc
Revises: 70b91cccee15
Create Date: 2021-02-23 12:13:27.503014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0eb5916ecc'
down_revision = '70b91cccee15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('attachment',
    #sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    #sa.Column('type', sa.String(length=5), nullable=False),
    #sa.Column('title', sa.String(length=200), nullable=True),
    #sa.Column('url', sa.String(length=300), nullable=False),
    #sa.Column('thumbnail', sa.Text(), nullable=True),
    #sa.Column('update_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['update_id'], ['update.id'], name='fk_attachment_update_id'),
    #sa.PrimaryKeyConstraint('id')
    #)
    #with op.batch_alter_table('update', schema=None) as batch_op:
    #    batch_op.drop_column('attachments')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.VARCHAR(), nullable=False))

    op.drop_table('attachment')
    # ### end Alembic commands ###
