"""Move cascade options to parents

Revision ID: 667c160db630
Revises: 1e2ed811e88d
Create Date: 2021-01-13 11:45:54.683301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667c160db630'
down_revision = '1e2ed811e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('o_auth1_token', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('scheduled_job', schema=None) as batch_op:
        batch_op.alter_column('update_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_job', schema=None) as batch_op:
        batch_op.alter_column('update_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('o_auth1_token', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
