"""Use realm_type name

Revision ID: 7b8c5950c5cc
Revises: 94f3d08496e0
Create Date: 2021-01-13 08:32:22.953796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8c5950c5cc'
down_revision = '94f3d08496e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm_type', sa.String(), nullable=False))
        batch_op.drop_column('realm_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('realm_type')

    # ### end Alembic commands ###
