"""Add multi realm updates

Revision ID: 7cd00819c52b
Revises: 8ade5a6fdc00
Create Date: 2021-10-29 01:56:49.749251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd00819c52b'
down_revision = '8ade5a6fdc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realm',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_realm',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('update_id', 'realm_id')
    )
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.drop_column('realm_id')
        batch_op.drop_column('realm_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm_type', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('realm_id', sa.VARCHAR(length=30), nullable=False))

    op.drop_table('update_realm')
    op.drop_table('realm')
    # ### end Alembic commands ###
