"""Change single parent position

Revision ID: 94f3d08496e0
Revises: 1995b16d172f
Create Date: 2021-01-12 22:38:48.910327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f3d08496e0'
down_revision = '1995b16d172f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm_name', sa.String(), nullable=False))
        batch_op.drop_column('realm')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school_id')
        batch_op.drop_column('building_id')

    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('realm_name')

    # ### end Alembic commands ###
